version: "3.9"

services:
  app:
    build: .
    container_name: sistema-lp
    restart: always
    env_file:
      - .env
    # 👇 MUDANÇA 1: Trocamos o bloqueio público 'ports' pelo acesso interno 'expose'
    expose:
      - "3000"
    # 👇 MUDANÇA 2: Conectamos o contêiner à nossa ponte de comunicação
    networks:
      - rede-proxy

# 👇 MUDANÇA 3: Avisamos ao arquivo que essa rede já foi criada no servidor
networks:
  rede-proxy:
    external: true
