versão: "3.9"

Serviços:
  aplicativo:
    construir: .
    nome_do_container: sistema-lp
    reiniciar: sempre
    arquivo_de_ambiente:
      - .env
    # 👇 MUDANÇA 1: Trocamos o bloqueio público 'portas' pelo acesso interno 'expose'
    Vale:
      - "3000"
    # 👇 MUDANÇA 2: Conectamos o contêiner à nossa ponte de comunicação
    redes:
      - rede-proxy

# 👇 MUDANÇA 3: Avisamos ao arquivo que essa rede já foi criada no servidor
redes:
  rede-proxy:
    externo: verdadeiro
